// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBzgVKz92QH56FkzAOiAYNV837_UttG1E',
    appId: '1:1075485437665:web:8e58158161c39df35ed1a0',
    messagingSenderId: '1075485437665',
    projectId: 'task-management-app-6db25',
    authDomain: 'task-management-app-6db25.firebaseapp.com',
    storageBucket: 'task-management-app-6db25.appspot.com',
    measurementId: 'G-CNZXT350V7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgv22U0cdk3VFaa0xZckCusrbbHzYJsdA',
    appId: '1:1075485437665:android:864393fa2728b3a75ed1a0',
    messagingSenderId: '1075485437665',
    projectId: 'task-management-app-6db25',
    storageBucket: 'task-management-app-6db25.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNPItOqUmI3EKvY7coqeWhpD-KNaQwTYw',
    appId: '1:1075485437665:ios:68c2fa719a24ca6b5ed1a0',
    messagingSenderId: '1075485437665',
    projectId: 'task-management-app-6db25',
    storageBucket: 'task-management-app-6db25.appspot.com',
    androidClientId: '1075485437665-9eavf6hp4lp9c3vkrlbos513qa71eg58.apps.googleusercontent.com',
    iosClientId: '1075485437665-f7g4da8i4i1vad7d17hsbfke8dq29he5.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNPItOqUmI3EKvY7coqeWhpD-KNaQwTYw',
    appId: '1:1075485437665:ios:660361aa6db973eb5ed1a0',
    messagingSenderId: '1075485437665',
    projectId: 'task-management-app-6db25',
    storageBucket: 'task-management-app-6db25.appspot.com',
    androidClientId: '1075485437665-9eavf6hp4lp9c3vkrlbos513qa71eg58.apps.googleusercontent.com',
    iosClientId: '1075485437665-vrr40t79pdnkctrp6arrk7kui36ko9hg.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskManagementApp.RunnerTests',
  );
}
